version: "3.3"
services:
  postgres:
   image: postgres:10.6
   container_name: postgres
   restart: always
   volumes:
    - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on:
    - postgres
    ports:
    - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: password
  graphql-engine:
    image: hasura/graphql-engine:latest
    container_name: hasura
    restart: always
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/example
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecret
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"jwtsecret of 32 characters or more"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
volumes:
  pgdb_init:
